wandb_version: 1

learning_rate:
  desc: null
  value: 0.03
epochs:
  desc: null
  value: 10
architecture:
  desc: null
  value: Vision Transformer
dataset:
  desc: null
  value: Tiny-Food101
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1724924802
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.17.7
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
